name: Dependency updater
on:
  push:
    branches:
      - 'build/**'
  schedule:
    - cron: '* 2 * * * '

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Init Git on runner
        run: |
          git config user.email "${{ secrets.GIT_USER_MAIL }}"
          git config user.name "github-actions"

      - name: npm install
        run: npm ci

      - name: Update dependencies
        run: npm run update

      - name: Push commit if available
        run: git push
